Merge dev into master
FreeNowOrg/PixivNow pull request #19
Opened 2022-03-15 08:58 UTC by AlPha5130

2022-03-24 18:25 UTC, Dragon-Fish commented
路由跳转时，侧边导航不会隐藏

2022-03-24 18:28 UTC, Dragon-Fish commented
“顶部导航栏在页面滚动到顶部时使用透明背景并隐藏搜索框”仅应出现在 home 路由中，但它在所有路由中都生效了

2022-03-24 18:30 UTC, Dragon-Fish commented
Gallery 组件中，分页器失去了圆角，分页器中“当前展示的图片”失去了底边蓝条

2022-03-24 18:32 UTC, Dragon-Fish commented
由 artworks 跳转到另一 artworks 路由时，“加载中”提示丢失

2022-03-24 18:34 UTC, Dragon-Fish commented
home 路由的“探索发现”列表未按预期缓存，它在每次 mounted 时均会重新请求随机列表

2022-03-26 08:31 UTC, AlPha5130 commented
已修复上述问题

2022-03-29 11:00 UTC, Dragon-Fish requested changes
search 路由中：

1. 分页器中的页码丢失了
2. 当位于第一页时，“上一页”按钮的 disabled 状态丢失了

其他暂时没发现什么问题 :)

2022-03-29 11:03 UTC, Dragon-Fish commented
另外问一下，为什么要把 search 中的作品列表替换成 mini 的

2022-03-29 11:04 UTC, Dragon-Fish commented
首页“探索发现”中，点击刷新后的 loading 状态丢失了

2022-04-01 05:33 UTC, Dragon-Fish requested changes
首页下的“探索发现”版块的“换一批”点击后的加载中状态丢失

修完这个应该就没啥了。

改个版本号。

2022-04-01 05:35 UTC, Dragon-Fish commented
顺便把这个删了吧，太丑了我天

![](https://user-images.githubusercontent.com/44761872/161201390-70d1a3ef-014a-4d83-94be-3a075c0bdc04.png)

2022-04-02 13:27 UTC, Dragon-Fish approved these changes
LGTM

辛苦了

2022-04-02 13:48 UTC, merged